### PR TITLE
#Add ticket booking page completed (Issue #8) 

### LINKED ISSUE #8: Add ticket booking page
Ticket Booking page should contain the list of various shows and videos and live stream and their respective pricing also both in online or offline mode ,It also contain the option to attend the shows etc in online or offline mode .If user click any of the list item it redirect to new page of their respective item and user have to fill the ticket form

### PR DESCRIPTION
**Pull request by vishal2005025**
# closes #8

### CODE REVIEW

**Comment by vishal2005025** [comment]
sir , please review and merge this issue..please..
Name : Vishal Malyan

**Comment by vishal2005025** [comment]
sir , please merge this issue ..

**Comment by 02shreyansh** [comment]
@vishal2005025, I am able to book tickets that are already marked as booked. Can you please resolve this issue?

**Comment by 02shreyansh** [comment]
@vishal2005025 ,all are good ,but please  resolve this issue

**Pull request closed without merging**
