### PR TITLE
added mars images feature

### PR DESCRIPTION
**Pull request by PranavBarthwal**
Added fetching martian images feature
fixes issue #75 

before entering the date
image

after entering the date
Screenshot (98)

### CODE REVIEW

**Comment by PranavBarthwal** [comment]
@02shreyansh Can you please tell if the current contact us section is functional or not?
If not then I'll be raising an issue for the same.
Thanks.

**Comment by PranavBarthwal** [comment]
@02shreyansh please do review this PR

**Comment by 02shreyansh** [comment]
@PranavBarthwal ,I will review it tomorrow, there's a slight network issue today.

That's why I am addressing the issue through my phone.

**Comment by PranavBarthwal** [comment]
> @PranavBarthwal ,I will review it tomorrow, there's a slight network issue today.
> 
> That's why I am addressing the issue through my phone.

No issues.

**Comment by 02shreyansh** [comment]
@PranavBarthwal ,You can raise the issue for contact us .

**Pull request merged**
